### ISSUE TITLE
Inverse relationship freeze frame is incorrect

### ISSUE THREAD

**Issue by DanyalAndriano** [learn-co-curriculum/multivariable-calculus-gradient-descent#2]
The panel in the top left shows f(-1, y) = y*-1^2 . However, there can be no inverse relationship when x is negative because it is squared. The y would have to be negative. 

![freeze_frames_partial derivatives](https://user-images.githubusercontent.com/41343236/44604334-88265c00-a7b3-11e8-8ae3-76009b1666bf.png)

**Comment by mas16** [comment]
Hi DanyalAndriano, thank you for pointing this out. The figure has been updated.
