### ISSUE TITLE
It appears graphs are incorrect on 'One more example'

### ISSUE THREAD

**Issue by rwilleynyc** [learn-co-curriculum/multivariable-calculus-gradient-descent#3]
Lab says f(x, y) = yx**2, and that when x = -1, f(y) = -1y. However, wouldn't x**2 turn the negative 1 into a positive 1? It the corresponding graph says shows a slope of -1 as well, but that doesn't make sense to how I would visualize the graph either. I think there is a logic error in this portion of the lab. If I am simply misunderstanding something, please let me know. Thanks!

<img width="892" alt="screen shot 2018-09-07 at 7 58 28 pm" src="https://user-images.githubusercontent.com/42759260/45247908-2862a180-b2d9-11e8-8d28-5b419491f869.png">
<img width="661" alt="screen shot 2018-09-07 at 8 00 38 pm" src="https://user-images.githubusercontent.com/42759260/45247909-2862a180-b2d9-11e8-9c5e-2645553270eb.png">

**Comment by mas16** [comment]
Hi rwilleynyc, thank you for pointing this out. The figure has been updated.
